"""empty message

Revision ID: 22081e448f03
Revises: a9ec7449f302
Create Date: 2019-11-24 12:59:29.582857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22081e448f03'
down_revision = 'a9ec7449f302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_category', sa.Column('status', sa.CHAR(), nullable=True))
    op.create_index(op.f('ix_budget_category_status'), 'budget_category', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budget_category_status'), table_name='budget_category')
    op.drop_column('budget_category', 'status')
    # ### end Alembic commands ###
