"""unallocated income column added to user table

Revision ID: 8ff636c026fb
Revises: bfdb0ab4567d
Create Date: 2019-11-29 22:25:02.730382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ff636c026fb'
down_revision = 'bfdb0ab4567d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('unallocated_income', sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'unallocated_income')
    # ### end Alembic commands ###
