"""empty message

Revision ID: b836b3eb9b8b
Revises: 22081e448f03
Create Date: 2019-11-24 13:14:52.912265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b836b3eb9b8b'
down_revision = '22081e448f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('ttype', sa.CHAR(), nullable=True))
    op.create_index(op.f('ix_transaction_amount'), 'transaction', ['amount'], unique=False)
    op.create_index(op.f('ix_transaction_ttype'), 'transaction', ['ttype'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_ttype'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_amount'), table_name='transaction')
    op.drop_column('transaction', 'ttype')
    # ### end Alembic commands ###
