"""added spending category to budget table

Revision ID: bfdb0ab4567d
Revises: 7f80f3531b38
Create Date: 2019-11-26 16:04:58.601288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfdb0ab4567d'
down_revision = '7f80f3531b38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_category', sa.Column('spending_category', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_budget_category_spending_category'), 'budget_category', ['spending_category'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budget_category_spending_category'), table_name='budget_category')
    op.drop_column('budget_category', 'spending_category')
    # ### end Alembic commands ###
