"""empty message

Revision ID: f7558a7926b6
Revises: 14ed358aecd9
Create Date: 2020-01-16 15:46:50.734160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7558a7926b6'
down_revision = '14ed358aecd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_transaction', sa.Integer(), nullable=True),
    sa.Column('dotm', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_transaction'], ['transaction.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_transaction_dotm'), 'scheduled_transaction', ['dotm'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_transaction_dotm'), table_name='scheduled_transaction')
    op.drop_table('scheduled_transaction')
    # ### end Alembic commands ###
